### ISSUE TITLE
Download Tutorial

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/regex-tutorial#96]
I would like to have a download functionality for the tutorial: I would like to be able to download the tutorial as a zip archive. This can not be the github repository archive as this is only the source code.

Hints for implementation:
- [x] use the travis automated build to zip the archive (see [.travis.yml](https://github.com/CoderDojoPotsdam/regex-tutorial/blob/master/.travis.yml) file) #97
- [x] upload the built archive to the github releases ([example](https://github.com/CodersOS/meilix/blob/a997d66db203841845ef10af7240729221bfbc33/.travis.yml#L17)) #97
- [x] Create a download button to download the latest release ([example](https://github.com/niccokunzmann/download_latest)) #98

If you like to work on this, please comment. If you have any questions, please comment. We are here to help :)

**Comment by niccokunzmann** [comment]
To verify that it can be downloaded, 

- check it there are releases turning up: https://github.com/CoderDojoPotsdam/regex-tutorial/releases
- See if the download button works.

**Comment by niccokunzmann** [comment]
Download works.
